### ISSUE TITLE
Missing step to switch to jquery-ajax branch after cloning library-api

### ISSUE THREAD

**Issue by laurenfazah** [ga-wdi-boston/wdi_6_demo_ajax_get#10]
(During Antony's training)

**Comment by jrhorn424** [comment]
@laurenfazah @gaand Does this just mean developers should switch to a new branch on the API, or a new branch in the client (this repository)?

**Comment by gaand** [comment]
I think it's branch on library-api, because we're changing `config/secrets.yml`.

**Comment by jrhorn424** [comment]
OK. I didn't have them do that this time, but I'll add it over at `library-api`.

**Comment by gaand** [comment]
It should be in the instructions here as well.

**Comment by jrhorn424** [comment]
Even considering #18?

**Comment by jrhorn424** [comment]
I've added `library-api` to our calendar as a block. I know it isn't a full point estimate, but maybe it's really a `library-api` guide? If we end up using this for multiple lessons, I'd hate to maintain instructions in two places. As it is now, they're already in two places.

**Comment by gaand** [comment]
If `library-api` is used for other talks (e.g. `handlebars`), then putting instructions specific to the `jquery-ajax-*` set into it seems incorrect.

**Comment by laurenfazah** [comment]
All set with latest 013/master merge @jrhorn424 @gaand

**Comment by jrhorn424** [comment]
Looks good. @gaand ?
