### ISSUE TITLE
Change GET /books/:id to lab

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/wdi_6_demo_ajax_get#15]
As a finish to the training.

**Comment by jrhorn424** [comment]
I'm going to hold off on this change for the moment. I want to see if this delivery finishes the show functionality. I'll add notes on my delivery to the planning card in either case.

**Comment by laurenfazah** [comment]
All set with latest 013/master merge @jrhorn424 @gaand

**Comment by jrhorn424** [comment]
Ok with closing. @gaand ?
