### ISSUE TITLE
Remove API instructions in favor of maintaining them in the API repo

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/wdi_6_demo_ajax_get#18]
Link to API repo in this talk with instructions to follow the instructions there. 😄

**Comment by jrhorn424** [comment]
I've added `library-api` to our calendar as a block. I know it isn't a full point estimate, but maybe it's really a `library-api` guide? If we end up using this for multiple lessons, I'd hate to maintain instructions in two places. As it is now, they're already in two places.

**Comment by laurenfazah** [comment]
All set with latest 013/master merge @jrhorn424

**Comment by jrhorn424** [comment]
Excellent. Thanks @laurenfazah
