### ISSUE TITLE
explicit user event to prevent server hang

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/wdi_6_demo_ajax_get#6]
Students had getItem and getItems() in their init file and ran, caused server to hang.  Antony suggested adding an explicit user event to prevent this in the future.  In class correction was to comment out lines before running.

**Comment by jrhorn424** [comment]
I basically DDOS'd myself. If I forget the context of this bug, I should just quit.

**Comment by jrhorn424** [comment]
I requested this to be filed. Developers now setup a local server and use that, so it should no longer be an issue.
