### ISSUE TITLE
Name handlers and move them into a separate file. 

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/wdi_6_demo_ajax_get#9]
See https://github.com/ga-wdi-boston/planning/issues/5
(Formerly https://github.com/ga-wdi-boston/010/issues/4)

**Comment by jrhorn424** [comment]
I believe this has largely been addressed by current talk scaffolding. @gaand Can you confirm?

I'm planning on naming all handlers. Blank files have been provided and scaffolding has been written to separate concerns during the talk.

**Comment by gaand** [comment]
It's not really possible to use unnamed handlers given the scaffolding, so I'll close this.
